/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as millerSol from "./miller.sol";
export type { millerSol };
export type { Greeter } from "./Greeter";
