/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Karoke__factory } from "./Karoke__factory";
export { RandomNumberGen__factory } from "./RandomNumberGen__factory";
